### ISSUE TITLE
Crear página crear caso

### ISSUE THREAD

**Issue by marielsgtzz** [ITAM-ADSI-2023/Linces-ProyectoFinal#13]
- [x] Crear página HTML
- [x] Crear formulario datos caso
    -Input y label:
          -Nombre
          -Iniciales
          -Descripción
    -Dropdown:
          -Tipo
          -Estado
    -Fecha
- [x] Agregar botón para regresar a portal
- [x] Agregar botón para crear caso

**Comment by Thiago-whatever** [comment]
![Image](https://user-images.githubusercontent.com/85588937/235069864-bb5f5fd1-be5c-463f-9c69-368b0bb5b4c7.png)
