### ISSUE TITLE
Crear página detalles caso

### ISSUE THREAD

**Issue by marielsgtzz** [ITAM-ADSI-2023/Linces-ProyectoFinal#16]
- [x] Crear página HTML
 - [x] Descripción caso (labels)
 - [x] Nombre caso (label)
 - [x] Estatus caso (label y dropdown)
 - [x] Espacio clickeable versiones finales
 - [x] Espacio clickeable borrador y correcciones
 - [x] Espacio clickeable información del caso
 - [x] Agregar botón para regresar a portal
 - [x] Agregar botón para agregar tarea
 - [x] Tabla tareas
     -  Título tarea
     -  Asignadx
     -  Fecha entrega
     - Status
     - Nota

**Comment by AngelAlva** [comment]
![Image](https://user-images.githubusercontent.com/68837629/235062219-2b811018-ef75-45a3-8c2a-f0d92e9fd708.png)
