### ISSUE TITLE
Crear página información (archivos) caso

### ISSUE THREAD

**Issue by marielsgtzz** [ITAM-ADSI-2023/Linces-ProyectoFinal#19]
- [x] Crear página HTML
- [x] Agregar botón para subir archivo
- [x] Agregar botón para regresar a información del caso
- [x] Agregar botón para regresar al portal
- [x] Colocar grid
    - En cada casilla de la grid poner el nombre de un documento y el botón para poder descargarlo

**Comment by AngelAlva** [comment]
![Image](https://user-images.githubusercontent.com/68837629/235066547-4af66896-7003-42f4-9da1-de2c80944a3e.png)
