### ISSUE TITLE
Crear página de inicio de sesión

### ISSUE THREAD

**Issue by marielsgtzz** [ITAM-ADSI-2023/Linces-ProyectoFinal#2]
- [x] Crear página HTML 
- [x] Incluir logo clínica
- [x] Formulario de inicio de sesión: 
- label y text inputs para nombre usuarix y contraseña (que no enseñe el valor de la contra)
- [x] Botón de inicio de sesión

**Comment by AngelAlva** [comment]
![Image](https://user-images.githubusercontent.com/68837629/235057134-2291bf96-2458-4560-9124-90dc016ee1bd.png)
