### ISSUE TITLE
Crear página para agregar tarea

### ISSUE THREAD

**Issue by marielsgtzz** [ITAM-ADSI-2023/Linces-ProyectoFinal#23]
- [x] Crear página html
- [x] Título página
- [x] Dropdown con los estudiantes registradxs
- [x] Campo de fecha
- [x] Dropdown para estatus
- [x] Dropdown para asignadx
- [x] Textarea para nota
- [x] Botón para agregar tarea
- [x] Botón para regresar al portal
- [x] Botón para regresar a detalles del caso

**Comment by Thiago-whatever** [comment]
![Image](https://user-images.githubusercontent.com/85588937/235072577-14653380-6e70-45d2-a33d-b85252b41d21.png)
