### ISSUE TITLE
Crear página búsqueda caso

### ISSUE THREAD

**Issue by marielsgtzz** [ITAM-ADSI-2023/Linces-ProyectoFinal#28]
- [x] Crear página HTML
- [x] Título página
- [x] Input para búsqueda
- [x] Botón búsqueda
- [x] Tres dropdowns para los filtros
- [x] Grid en donde se va mostrar la lista de resultados
- [x] Botón para regresar a portal

**Comment by Thiago-whatever** [comment]
![Image](https://user-images.githubusercontent.com/85588937/235363729-9fee7740-e550-450e-9b24-785dfef75436.png)
