### ISSUE TITLE
Crear página portal Jessica y Donna

### ISSUE THREAD

**Issue by marielsgtzz** [ITAM-ADSI-2023/Linces-ProyectoFinal#4]
- [x] Crear página HTML
- [x] Mostrar el nombre del usuarix
- [x] Botón para crear caso
- [x] Botón para buscar caso
- [x] Botón de cierre de sesión

**Comment by Thiago-whatever** [comment]
![Image](https://user-images.githubusercontent.com/85588937/235056623-dd6baf54-8d1f-4e33-ac93-28b910d9e372.png)
