### ISSUE TITLE
Crear página portal Mike y Rachel

### ISSUE THREAD

**Issue by marielsgtzz** [ITAM-ADSI-2023/Linces-ProyectoFinal#5]
- [x] Modificar portal de Jessica y Donna (remover botón crear caso)
- [x] Lista de tareas 
    - Mostrar nombre, fecha entrega, texo para hacer click y revisar

**Comment by Thiago-whatever** [comment]
![Image](https://user-images.githubusercontent.com/85588937/235059304-89d0e6d7-6d8f-4e65-97b9-12705da88705.png)
